version: "3.1"

services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672

  movies:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:8000
    env_file:
      - .env # Ensure .env is in the same directory as docker-compose.yml
    command: npm run start
    depends_on:
      - redis
      - rabbitmq

  log:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:8001
    env_file:
      - .env # Ensure .env is in the same directory as docker-compose.yml
    command: npm run start
    depends_on:
      - redis
      - rabbitmq
